name: Setup Electron App
description: Checkout, Node.js, and install dependencies
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - id: get-node-version
      shell: bash
      run: |
        NODE_VERSION=$(grep '^node' .mise.toml | awk '{print $3}')
        echo "node_version=$NODE_VERSION" >> "$GITHUB_OUTPUT"
        echo "NODE_VERSION=$NODE_VERSION"

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ steps.get-node-version.outputs.node_version }}
        cache: 'yarn'

    - run: yarn install --frozen-lockfile
      shell: bash
