name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            artifact_path: out/make/deb/**/*.deb
          - os: windows-latest
            platform: windows
            artifact_path: out/make/squirrel.windows/**/*.exe
          - os: macos-latest
            platform: macos
            artifact_path: out/make/**/*.dmg

    runs-on: ${{ matrix.os }}
    name: Build for ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - id: get-node-version
        shell: bash
        run: |
          NODE_VERSION=$(grep '^node' .mise.toml | awk '{print $3}' | tr -d '"')
          echo "node_version=$NODE_VERSION" >> "$GITHUB_OUTPUT"
          echo "NODE_VERSION=$NODE_VERSION"

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.get-node-version.outputs.node_version }}
          cache: 'yarn'

      - run: yarn install
        shell: bash

      - name: Build with Electron Forge
        run: yarn make

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.artifact_path }}